artifact_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/NaVeen913/mlflow/main/gettingstarted.zip

  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion